config/routes.rb
Rails.application.routes.draw do
  # login / logout
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: :logout

  resources :tournaments, except: :index do
    resources :participants
  end

  resources :managements
  resources :participations

  resources :users, only: [:show, :edit, :update]

  root 'dashboard#index'
end

app/models/participation.rb
class Participation < ActiveRecord::Base
  belongs_to :participant, class_name: :User, foreign_key: :user_id
  belongs_to :tournament

  def tournament_id
    tournament.id
  end
end

app/controllers/participations_controller.rb
class ParticipationsController < ApplicationController
  before_action :set_participation, only: [:edit, :update, :destroy]
  before_action :set_tournament, only: [:index]
  before_action :set_users, only: [:new]
  before_action :check_login, only: [:new, :create, :edit, :update, :destroy]

  def index
    @participations = Participation.where(tournament_id: params[:t_id])
  end

  def new
    @participation = Participation.new(tournament_id: params[:t_id])

    render 'new'
  end

  def create
    @participation = Participation.new(participation_params)

    unless @participation.save
      render 'new'
      return
    end

    redirect_to participations_path(t_id: @participation.tournament_id), notice: t('view.create_success')
  end

  def edit
  end

  def update
    unless @participation.update(participation_params)
      render 'edit'
      return
    end

    redirect_to participations_url(t_id: @participation.tournament_id), notice: t('view.update_success')
  end

  def destroy
    @participation.destroy

    redirect_to participations_url(t_id: @participation.tournament_id), notice: t('view.destroy_success')
  end

  private

  def set_users
    @users = User.all
  end

  def set_tournament
    @tournament = Tournament.find(params[:t_id])
  end

  def set_participation
    @participation = Participation.find(params[:id])
  end

  def participation_params
    params.require(:participation).permit(:name, :user_id, :tournament_id)
  end
end

app/views/participations/_form.html.haml
.container-fluid.col-xs-6
  = form_for(@participation) do |f|
    - if @participation.errors.any?
      #error_explanation
        %h2 #{pluralize(@participation.errors.count, 'error')} prohibited this participation from being saved:
        %ul
          - @participation.errors.full_messages.each do |message|
            %li= message
    .form-group
      = f.label :tournament
      = @participation.tournament.name
      = f.hidden_field :tournament_id
    .form-group
      = f.label :participant
      %p
      - if @participation.new_record?
        = f.select :user_id, options_from_collection_for_select(@users, :id, :name), class: 'form-control'
      - else
        = @participation.participant.name
    .form-group
      = f.label :name
      %p
      = f.text_field :name, class: 'form-control', size: '10'
    .form-group
      = link_to t('view.back'), :back, { class: 'btn btn-success' }
      &nbsp;
      = f.submit t('submit'), class: 'btn btn-primary'

app/views/participations/edit.html.haml
= render 'form'

app/views/participations/index.html.haml
.container-fluid
  %table.table
    %tr
      %th
        = Participation.human_attribute_name(:name)
      %th
    - @participations.each do |pa|
      %tr
        %td
          = pa.name
        %td
          = link_to t('view.edit'), edit_participation_path(pa)
          |
          = link_to t('view.destroy'), pa, method: :delete, data: { confirm: t('view.destroy_confirm') }
  = link_to t('view.add'), new_participation_path(t_id: @tournament.id)
  |
  = link_to t('view.home'), root_path

app/views/participations/new.html.haml
= render 'form'