config/routes.rb
Rails.application.routes.draw do
  # login / logout
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: :logout

  resources :tournaments, except: :index do
    resources :participants
  end

  resources :managements
  resources :participations

  resources :users, only: [:show, :edit, :update]

  root 'dashboard#index'
end

app/models/tournament.rb
class Tournament < ActiveRecord::Base
  include Authority::Abilities
  include Searchable

  has_many :games
  has_many :managements, dependent: :destroy
  has_many :participations, dependent: :destroy
  has_many :managers, through: :managements
  has_many :participants, through: :participations

  scope :published, -> { where(published: true) }

  validates :name, presence: true

  DEFAULT_PARTICIPANT_COUNT = 4
  DEFAULT_GAEME_COUNT = DEFAULT_PARTICIPANT_COUNT - 1

  def self.create_with_content(attr)
    attr[:uuid] = SecureRandom.uuid
    @tournament = Tournament.new(attr)

    DEFAULT_PARTICIPANT_COUNT.times { @tournament.participants.build }
    DEFAULT_GAEME_COUNT.times { @tournament.games.build }

    @tournament.tap(&:save)
  end

  def staff?(user)
    m = managements.where(user_id: user).first
    m.nil? ? false : %w(owner collaborator).include?(m.role)
  end

  def owner?(user)
    m = managements.where(user_id: user).first
    m.nil? ? false : (m.role == 'owner')
  end
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  before_action :set_tournament, only: [:show, :edit, :update, :destroy]
  before_action :can_create?, only: [:new, :create]
  before_action only: [:edit, :update] { can_update?(@tournament) }
  before_action only: [:destroy] { can_delete?(@tournament) }

  def new
    @tournament = Tournament.new
  end

  def edit
  end

  def create
    management = Management.new(manager: current_user, role: 'owner')
    @tournament = Tournament.new(tournament_params.merge(managements: [management]))

    respond_to do |format|
      if @tournament.save
        format.html { redirect_to @tournament, notice: t('view.create_success') }
      else
        format.html { render :new }
      end
    end
  end

  def update
    @tournament.update(tournament_params)
    redirect_to tournament_path(@tournament)
  end

  def add_participation
    tournament = Tournament.find(params[:id])
    participation = tournament.participations.build

    participation.save
    redirect_to tournament_tournament_path(tournament)
  end

  def destroy
    @tournament.destroy
    redirect_to :root, notice: t('view.destroy_success')
  end

  private

  def set_tournament
    @tournament = Tournament.find(params[:id])
  end

  def tournament_params
    params.require(:tournament).permit(:name, :description, :opened_at, :published)
  end
end

app/views/tournaments/_form.html.haml
= form_for(@tournament) do |f|
  - if @tournament.errors.any?
    #error_explanation
      %h2 #{pluralize(@tournament.errors.count, "error")} prohibited this tournament from being saved:
      %ul
        - @tournament.errors.full_messages.each do |message|
          %li= message

app/views/tournaments/edit.html.haml
= form_for(@tournament) do |f|
  .container-fluid
    .col-xs-6
      .form-group
        = f.label :name
        = f.text_field :name, class: 'form-control'
      .form-group
        = f.label :opened_at
        %p
          = f.datetime_select :opened_at, class: 'form-control'
      .form-group
        = f.label :description
        = f.text_area :description, class: 'form-control'
      .form-group
        = f.label :published
        = f.check_box :published, class: 'form-control'
      .form-group
        = link_to t('view.back'), :back, { class: 'btn btn-success' }
        &nbsp;
        %button.btn.btn-primary
          = t('submit')

app/views/tournaments/new.html.haml
= javascript_include_tag 'tournament/new'

= form_for(@tournament) do |f|
  - if @tournament.errors.any?
    #error_explanation
      %h2 #{pluralize(@tournament.errors.count, 'error')} prohibited this tournament from being saved:
      %ul
        - @tournament.errors.full_messages.each do |message|
          %li= message
  .container-fluid
    #root-wizard.col-xs-6
      .navbar
        .navbar-inner
          .container
            %ul
              %li
                %a{ href: '#tab1', 'data-toggle' => 'tab' }
                  = t('view.tournament.new.basic_info')
              %li
                %a{ href: '#tab2', 'data-toggle' => 'tab' }
                  = t('view.tournament.new.terms')
      .progress
        .bar.progress-bar{ role: 'progress-bar', 'aria-valuemin' => '0', 'aria-valuemdax' => '100' }
      .tab-content
        #tab1.tab-pane
          .form-group
            = f.label :name
            = f.text_field :name, class: 'form-control'
          .form-group
            = f.label :opened_at
            %p
              = f.datetime_select :opened_at, class: 'form-control'
          .form-group
            = f.label :description
            = f.text_area :description, class: 'form-control'

        #tab2.tab-pane
          %p.text-center
            TODO: some terms and condition
          %p.text-center
            %input#acceptTerms.required{ name: 'acceptTerms', type: 'checkbox' }
            = t('accept_terms_and_condition')
        %ul.pager.wizard
          %li.previous.first{ style: 'display:none;' }
            %a{ href: '#' }
              = t('first')
          %li.previous
            %a{ href: '#' }
              = t('previous')
          %li.next.last{ style: 'display:none;' }
            %a{ href: '#' }
              = t('last')
          %li.next
            %a{ href: '#' }
              = t('next')
          %li.next.finish
            .form
              %button.btn.btn-primary.pull-right
                = t('create')

app/views/tournaments/publish.html.haml
= javascript_include_tag 'publish'

= render 'navigation'

.row
  .col-md-8.col-md-offset-2
    .panel.panel-info
      .panel-heading
        Publish
      .panel-body
        = form_for(@tournament) do |f|
          .form#form-values
            .form-group
              = f.label :published
            .form-group
              = f.check_box :published
          .form
            %button.btn.btn-primary#btn-publish
              Open / Close

app/views/tournaments/show.html.haml
.container-fluid
  %p#notice= notice

.container-fluid
  %table.table
    %tr
      %th
        = Tournament.human_attribute_name(:name)
      %td
        = @tournament.name
    %tr
      %th
        = Tournament.human_attribute_name(:description)
      %td
        = @tournament.description
    %tr
      %th
        = Tournament.human_attribute_name(:opened_at)
      %td
        = @tournament.opened_at
    %tr
      %th
        = Tournament.human_attribute_name(:published)
      %td
        = @tournament.published
  - if current_user.can_update?(@tournament)
    = link_to t('view.edit'), edit_tournament_path(@tournament)
    |
  - if current_user.can_delete?(@tournament)
    = link_to t('view.destroy'), tournament_path(@tournament), method: :delete, data: { confirm: t('view.destroy_confirm') }
    |
  = link_to t('view.participation.index.title'), participations_path(t_id: @tournament.id)
  |
  = link_to t('view.management.index.title'), managements_path(t_id: @tournament.id)
  |
  = link_to t('view.home'), root_path

app/views/tournaments/tournament.html.haml
= javascript_include_tag 'jcanvas'
= javascript_include_tag 'tournament'

= render 'navigation'

.row
  .col-md-8.col-md-offset-2
    .panel.panel-info
      .panel-heading
        Draw Tournament
      .panel-body
        .row
          = raw(@tournament_tags)
        .row
          = form_tag(controller: :tournaments , action: :add_participation) do
            %input.btn.pull-right{ type: :submit , value: 'Add Participation' }
            = link_to 'Go Next', publish_tournament_path(@tournament.id) , class: 'btn btn-primary pull-right' 