config/routes.rb
Rails.application.routes.draw do
  # login / logout
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: :logout

  resources :tournaments, except: :index do
    resources :participants
  end

  resources :managements
  resources :participations

  resources :users, only: [:show, :edit, :update]

  root 'dashboard#index'
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= Scoredoc2
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-default
      .container-fluid
        .navbar-header
          %a.navbar-brand{ href: '/' }= 'Scoredoc2'
        .navbar-form.navbar-right
          .form-group
            - if logged_in?
              = link_to t('view.nav.my_page'), user_path(current_user), { class: 'btn btn-success' }
              &nbsp;&nbsp;
              = link_to t('view.nav.create_tournament'), new_tournament_path, { class: 'btn btn-primary' }
              &nbsp;&nbsp;
              %a{ href: logout_path }= t('logout')
            - else
              %a{ href: '/auth/twitter' }= t('login')
    .container-fluid
      .center-block
        - if flash[:notice]
          .alert.alert-success
            = flash[:notice]
        - if flash[:error]
          .alert.alert-danger
            = flash[:error]
      .center-block
        = yield