config/routes.rb
Rails.application.routes.draw do
  # login / logout
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: :logout

  resources :tournaments, except: :index do
    resources :participants
  end

  resources :managements
  resources :participations

  resources :users, only: [:show, :edit, :update]

  root 'dashboard#index'
end

app/models/management.rb
class Management < ActiveRecord::Base
  belongs_to :manager, class_name: :User, foreign_key: :user_id
  belongs_to :managed_tournament, class_name: :Tournament, foreign_key: :tournament_id

  def owner?
    role == 'owner'
  end

  def collaborator
  end
end

app/controllers/managements_controller.rb
class ManagementsController < ApplicationController
  before_action :set_tournament, only: [:index]
  before_action :set_management, only: [:destroy]

  def index
    @managements = Management.where(tournament_id: params[:t_id])
  end

  def new
    @management = Management.new(tournament_id: params[:t_id])

    render 'new'
  end

  def create
    @management = Management.new(management_params)

    unless @management.save
      render 'new'
      return
    end

    redirect_to managements_url(t_id: @management.tournament_id), notice: t('view.create_success')
  end

  def destroy
    @management.destroy

    redirect_to managements_url(t_id: @management.tournament_id), notice: t('view.destroy_success')
  end

  private

  def set_tournament
    @tournament = Tournament.find(params[:t_id])
  end

  def set_management
    @management = Management.find(params[:id])
  end

  def management_params
    params.require(:management).permit(:role, :user_id, :tournament_id)
  end
end

app/views/managements/_form.html.haml
.container-fluid.col-xs-6
  = form_for(@management) do |f|
    - if @management.errors.any?
      #error_explanation
        %h2 #{pluralize(@management.errors.count, 'error')} prohibited this management from being saved:
        %ul
          - @management.errors.full_messages.each do |message|
            %li= message
    .form-group
      = f.label :tournament
      = @management.managed_tournament.name
      = f.hidden_field :tournament_id
    .form-group
      = f.label :manager
      %p
      - if @management.new_record?
        = f.select :user_id, options_from_collection_for_select(User.all, :id, :name), class: 'form-control'
      - else
        = @management.manager.name
    .form-group
      = f.label :role
      %p
      = f.select :role, options_from_collection_for_select(Role.all, :name, :name), class: 'form-control'
    .form-group
      = link_to t('view.back'), :back, { class: 'btn btn-success' }
      &nbsp;
      = f.submit t('submit'), class: 'btn btn-primary'

app/views/managements/index.html.haml
.container-fluid
  %table.table
    %tr
      %th
        = Management.human_attribute_name(:name)
      %th
        = Management.human_attribute_name(:role)
      %th
    - @managements.each do |mng|
      %tr
        %td
          = mng.manager.nickname
        %td
          = mng.role
        %td
          - if current_user.can_update?(@tournament)
            = link_to t('view.destroy'), mng, method: :delete, data: { confirm: t('view.destroy_confirm') }
  - if current_user.can_update?(@tournament)
    = link_to t('view.add'), new_management_path(t_id: @tournament.id)
    |
  = link_to t('view.home'), root_path

app/views/managements/new.html.haml
= render 'form'